

/* =====[ AKOSTAR WiFi Clock project ]====================================

   File Name:       main/page_4.html
   
   Description:     Main file

   Revisions:

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  mar.07.2018     Peter Glen      Initial version.

   ======================================================================= */

// Page contents

const char advanced_html [] = 

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">"
"<html>"
"<title>WiFi Clock Config</title>"
"</head>"
"<body>"
"<center>"
"<h1>WiFiClock Advanced Config Page</h1>"
"</center>"
"<style>"
".container {"
"	text-align: left;"
"	border: 1px solid green;"
"	padding: 5px;"
"}"
".container table {"
"	border: 1px solid red;        "
"    margin: 0 auto;"
"    }"
"    "
"</style>"
"<form method=post>"
"<table align=center>"
"<tr><td>"
"Select Time Server (NTP, SNTP) :&nbsp  "
"<td>"
"<select name=ntpsrv>"
"  <option value=\"129.6.15.28\"> time-a-g.nist.gov </option> "
"  <option value=\"129.6.15.29\"> time-b-g.nist.gov </option> "
"  <option value=\"129.6.15.30\"> time-c-g.nist.gov </option> "
"  <option value=\"129.6.15.27\"> time-d-g.nist.gov </option>   "
"  "
"  <option value=\"132.163.97.1\"> time-a-wwv.nist.gov </option>   "
"  <option value=\"132.163.97.2\"> time-b-wwv.nist.gov </option>   "
"  <option value=\"132.163.97.3\"> time-c-wwv.nist.gov </option>   "
"  <option value=\"132.163.97.4\"> time-d-wwv.nist.gov </option>   "
"  <option value=\"0.0.0.0\"> USE Custom (enter below)</option> "
"</select>"
"</tr>"
"<tr><td colspan=2 align=center>"
"</tr>"
"<tr><td colspan=2 align=center>"
"</tr>"
"<tr><td>"
"Use custom NTP IP address:&nbsp"
"<td>"
"<input name=ntpip type=text>"
"</tr>"
"<tr><td colspan = 2>"
"<hr>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:24px\">"
"<b>Clock Time at last Page Load:</b>"
"</div>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:100px\">"
"00:00"
"</div>"
"<tr><td colspan=2 align=center>"
"<tr><td colspan=2 align=center>"
"Last updated at: dd/mm/yyyy hh:mm"
"<tr><td colspan=2 align=center>"
"<tr><td colspan=2>"
"<hr>"
"<tr><td colspan=2 align=center>"
"</tr>"
"<tr><td colspan=2>"
"<div>"
"<center>"
"The custom time zone is provided in case your location<br>"
"does not appear in the drop down selection on the main page."
"</center>"
"</div>"
"<tr><td colspan=2 align=center>"
"</tr>"
"<tr><td colspan=2 align=center>"
"</tr>"
"<tr><td>"
"Use custom UTC Timezone Offset: &nbsp"
"<td>"
"<input name=tzcust type=text>"
"<tr><td colspan=2 align=center height=12>"
"</tr>"
"<tr><td colspan=2 align=center>"
"    <b>Custom Clock Color: (RGB 0 ... 255)</b>"
"</tr>"
"<tr><td colspan=2 align=center height=12>"
"</tr>"
"<tr><td>"
"Red: <td><input name=RR type=text value=00> &nbsp"
"</tr>      "
"<tr><td>"
"Green: <td><input name=GG type=text value=00> &nbsp"
"</tr>"
"<tr><td>"
"Blue: <td><input name=BB type=text value=00> &nbsp"
"</tr>"
"<tr><td colspan=2 align=center height=22>"
"</tr>"
"<tr><td colspan=2 align=center>"
"<input type=submit value='Save Configuration'>"
"</tr>"
"<tr><td colspan=2>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_1.html?home=true>Jump to Home page.</a>"
"</div>"
"<tr><td colspan=2 height=12>"
"</table>"
"</form>"
"</body>"
"</html>"
;
// EOF
