

/* =====[ AKOSTAR WiFi Clock project ]====================================

   File Name:       main/page_1.html
   
   Description:     Main file

   Revisions:

      REV   DATE            BY              DESCRIPTION
      ----  -----------     ----------      ------------------------------
      0.00  mar.07.2018     Peter Glen      Initial version.

   ======================================================================= */

// Page contents

const char index_html [] = 

"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">"
"<html>"
"<title>WiFi Clock Config</title>"
"</head>"
"<body>"
"<center>"
"<h1>WiFiClock Config Page</h1>"
"</center>"
"<style>"
".container {"
"	text-align: left;"
"	border: 1px solid green;"
"	padding: 5px;"
"}"
".container table {"
"	border: 1px solid red;        "
"    margin: 0 auto;"
"    }"
"    "
"</style>"
"\n"
"<form method=post>"
"<table align=center>"
"\n"
"<tr> <td>"
"Select Time zone:&nbsp  "
"<td>"
"\n"
"<select name=tzone>"
"    <option value=\"HST+10\" selected> Hawaii Standard Time (HST)   [UTC-10] </option>\n"
"    <option value=\"AKST+9\" selected> Alaska Standard Time (AKST) [UTC-9]  </option> \n"
"    <option value=\"PST+8\" selected> Pacific Standard Time (PST)  [UTC-8]  </option> \n"
"    <option value=\"MST+7\" selected> Mountain Standard Time (MST) [UTC-7]  </option> \n"
"    <option value=\"CST+6\" selected> Central Standard Time (CST)  [UTC-6]  </option> \n"
"    <option value=\"EST+5\" selected> Eastern Standard Time (EST)  [UTC-5]  </option> \n"
"    <option value=\"AST+4\" selected> Atlantic Standard Time (AST) [UTC-4]  </option> \n"
"    <option value=\"---\"           > ----------------------------------    </option> \n"
"    <option value=\"WET-0\" selected> Western European Time (WET)  [UTC+0]  </option> \n"
"    <option value=\"CET-1\" selected> Central European Time (CET)  [UTC+1]  </option> \n"
"    <option value=\"EET-2\" selected> Eastern European Time (EET)  [UTC+2]  </option> \n"
"    <option value=\"FET-3\" selected> Further European Time (FET)  [UTC+3]  </option> \n"
"    <option value=\"---\"           > ----------------------------------    </option> \n"
"    <option value=\"CUS\"   selected> Custom (set in advanced section)      </option> \n"
"</select>"
"</tr>"
"\n"
"\n"
"><td>Daylight savings time:&nbsp"
"<td>"
"<input id=dst type=checkbox name=dst checked>"
"<tr><td colspan=2 height=12>"
"\n"
"<tr> <td>"
"Time update interval:&nbsp  "
"<td>"
"\n"
"<select name=\"tupdate\">"
"    <option value=\"004\" selected>  4 minutes </option> \n"
"    <option value=\"240\" selected>  4 hours </option>   \n"
"    <option value=\"480\" selected>  8 hours </option>   \n"
"</select>"
"\n</tr>"
"<tr><td colspan=2 height=12>"
"\n"
"<tr><td>"
"Brightness:&nbsp  "
"<td>"
"<select name=bright>"
"    <option value=\"010\" selected> 10% </option> \n"
"    <option value=\"020\" selected> 20% </option> \n"
"    <option value=\"030\" selected> 30% </option> \n"
"    <option value=\"040\" selected> 40% </option> \n"
"    <option value=\"050\" selected> 50% </option> \n"
"    <option value=\"060\" selected> 60% </option> \n"
"    <option value=\"070\" selected> 70% </option> \n"
"    <option value=\"080\" selected> 80% </option> \n"
"    <option value=\"090\" selected> 80% </option> \n"
"    <option value=\"100\" selected>100% </option> \n"
"</select>"
"</tr>"
"\n"
"<td>"
"Color:&nbsp  "
"<td>"
"\n"
"<select name=\"color\">"
"    <option value=\"RR\" selected> Red </option>    \n"
"    <option value=\"GG\" selected> Green </option>  \n"
"    <option value=\"BB\" selected> Blue </option>   \n"
"    <option value=\"RB\" selected> Purple</option>  \n"
"    <option value=\"RG\" selected> Teal</option>    \n"
"    <option value=\"GB\" selected> Yellow</option>  \n"
"    <option value=\"WW\" selected> White </option>  \n"
"    <option value=\"CU\" selected> Custom </option> \n"
"</select>"
"</tr>"
"\n"
"<td colspan=2 height=12>"
"<tr><td>24 hour display:&nbsp"
"<td>"
"<input id=ampm type=checkbox name=ampm checked>"
"<tr><td colspan=2 height=12>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_2.html?home=true>Jump to Access Point config page.</a>"
"</div>"
"<tr><td colspan=2>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_3.html?home=true>Jump to Station Config page.</a>"
"</div>\n"
"<tr><td colspan=2>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_4.html?home=true>Jump to Advanced Config page.</a>"
"</div>\n"
"<tr><td colspan=2>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_1.html?refresh=true>Refresh time from Time Server.</a>"
"</div>\n"
"<tr><td colspan=2>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:large\">"
"<a href=page_1.html?reboot=true>Reboot WifiClock.</a>"
"</div>\n"
"\n"
"<td colspan=2 height=12>"
"<tr><td colspan = 2>"
"<hr>"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:24px\">"
"<b>Clock Time at last Page Load:</b>"
"</div>\n"
"<tr><td colspan=2 align=center>"
"<div style=\"font-size:100px\">"
"00:00"
"</div>\n"
"<tr><td colspan=2 align=center>"
"<tr><td colspan=2 align=center>"
"Last updated at: dd/mm/yyyy hh:mm"
"<tr><td colspan=2 align=center>"
"<tr><td colspan=2>"
"<hr>"
"\n"
"<td colspan=2 align=center height=12>"
"</tr>"
"<tr><td colspan=2 align=center>"
"<input type=submit value='Save Configuration'>"
"</tr>   \n"
"</table>"
"</form>"
"</body>"
"</html>"
;
// EOF
